User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
Error 2021-09-07 01:07:38: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/.config/Code/User/settings.json')
	at _handleError (/home/chrispro-1/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at async y.readText (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async p.doesFileNeedToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:823850)
	at async /home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822977
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822923)
	at async p.updateTestSettings (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822550)] {
  code: 'FileNotFound'
}
Error 2021-09-07 01:07:38: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/csc4350-lecture4-materials/.vscode/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a2235322e3135322e3233382e3138222c2275736572223a22636872697370726f2d31227d/home/chrispro-1/csc4350-lecture4-materials/.vscode/settings.json')
	at _handleError (/home/chrispro-1/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at async y.readText (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:9:315784)
	at async p.doesFileNeedToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:823850)
	at async /home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822977
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822923)
	at async p.updateTestSettings (/home/chrispro-1/.vscode-server/extensions/ms-python.python-2021.9.1191016588/out/client/extension.js:59:822550)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Python interpreter path: /bin/python3
> conda --version
Error 2021-09-07 01:11:06: Error while running worker[Worker 2]. undefined
Error 2021-09-07 01:11:06: Error while running worker[Worker 1]. undefined
